{
 "title": "Meshthastic",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "TEST",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  l.timestamp,\r\n  s.short_name AS sender,\r\n  r.short_name AS receiver,\r\n  l.hops,\r\n  l.nodecount,\r\n  l.duration,\r\n  l.message\r\nFROM log_test l\r\nLEFT JOIN nodes s ON l.sender_node_id = s.id\r\nLEFT JOIN nodes r ON l.recipient_node_id = r.id\r\nORDER BY l.timestamp DESC;\r\n"
    }
   ]
  },
  {
   "title": "MediumFast",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  l.timestamp,\r\n  s.short_name AS sender,\r\n  r.short_name AS receiver,\r\n  l.hops,\r\n  l.nodecount,\r\n  l.duration,\r\n  l.message\r\nFROM log_mediumfast l\r\nLEFT JOIN nodes s ON l.sender_node_id = s.id\r\nLEFT JOIN nodes r ON l.recipient_node_id = r.id\r\nORDER BY l.timestamp DESC;\r\n"
    }
   ]
  },
  {
   "title": "Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT * FROM log_raw ORDER BY timestamp DESC;\r\n"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 24 },
   "targets": [
    { "rawSql": "SELECT * FROM nodes;\r\n" }
   ]
  }
 ]
}